### PR TITLE
rabbitmq and port hardening

### PR DESCRIPTION
**Pull request by bne86**
This PR addresses #1423 but also introduces the configuration of rabbitmq username/password. And, it should be possible to use alpine images for rabbitmq/redis.

### CODE REVIEW

**Comment by emanueldima** [comment]
Why make all these drastic changes? Isn't it better to keep the old config and use ports without publishing them to the host? i.e. use expose? https://docs.docker.com/compose/compose-file/compose-file-v2/#/expose

**Comment by bne86** [comment]
The compose file that i started with was vulnerable. Both because a default username/password was used and because the port was accessible through the (maybe only local) network.

In our environment completely removing the port section (simply relying on the links mechanism) works well, using "expose" was not necessary. So, i did not see any reason for this.

Simply removing the ports section was the fastest but tested solution for the given problem, i also do not think that is it "drastic". But, feel free to use "expose" instead. I am not a b2share developer, i only want to share the solution that works for our deployment.

**Comment by emanueldima** [comment]
Indeed, thank you for the PR and for signalling the issue; we have to discuss internally how to fix this best.

**Comment by emanueldima** [comment]
merged via https://github.com/EUDAT-B2SHARE/b2share/pull/1462

**Pull request closed without merging**
