### PR TITLE
Vagrant environment update

### PR DESCRIPTION
**Pull request by emanueldima**
Commented out the yum system update in the provisioning scripts, which seems to fix the vagrant sync issues

### CODE REVIEW

**Comment by dblommesteijn** [comment]
I'm not sure about the custom `./install.sh` script, instead of `vagrant up`.

**Comment by emanueldima** [comment]
@dblommesteijn I agree, we should automate this. New issue?

**Comment by dblommesteijn** [comment]
You can just fix it with this PR I think.

**Comment by emanueldima** [comment]
@dblommesteijn Won't happen until the end of next week. This PR fixes a big and different issue

**Comment by dblommesteijn** [comment]
I've got an issue with the installation of current `master` install, will this PR fix it?

**Pull request merged**
