### PR TITLE
Testing b2share and only b2share

### PR DESCRIPTION
**Pull request by emanueldima**
This PR is not necessarily meant to be merged, but more like a question. I couldn't find a way to run **only** the b2share tests, so I added the python code check below.

### CODE REVIEW

**Comment by emanueldima** [comment]
@jirikuncar @lnielsen @nharraud @dblommesteijn Is there a way to run tests in a certain package?

**Comment by dblommesteijn** [comment]
@emanueldima  Yes there is, but what do you mean by `package`?

**Comment by emanueldima** [comment]
@dblommesteijn I want to run only the tests in invenio.b2share.testsuite. I tried using
````
python setup.py test --test-suite invenio.b2share.testsuite
````
and I get:
````
AttributeError: 'module' object has no attribute 'testsuite'
````

**Comment by dblommesteijn** [comment]
Yes, that's because you've used the unmodified version of `setup.py` and others, check the changes I've made to the setup. Basically the Invenio implementation is misusing the default python unit-test suite. With my changes I've fixed it.

**Comment by emanueldima** [comment]
@nharraud Is this fix (see above) something you want to merge into invenio?

**Comment by lnielsen** [comment]
In an overlay you can run only specific tests using the ``TEST_SUITES`` config variable (i.e. you want to run all B2SHARE tests but not Invenio tests). See example at:
https://github.com/zenodo/zenodo/blob/master/zenodo/config.py#L126-L134

Running a specific testsuite (either Invenio or B2SHARE) works for me with both:

```
python setup.py test --test-suite invenio.modules.webhooks.testsuite
``` 

or

```
cd invenio/modules/webhooks/testsuite
nosetest -s 
```

**Comment by nharraud** [comment]
@emanueldima as @lnielsen suggests, I have been using `nose` up to now when I needed to run some module's tests on Invenio. I use it like that:
```
nosetests --no-skip invenio/modules/authors/testsuite
```

I tried to run some module's tests with `setup.py` and had not issue on Invenio master branch.  When I try that on B2Share 1.4 and master the tests are running correctly but I get an exception at the end.
```
python setup.py test --test-suite invenio.modules.authors.testsuite

...

test_user_deletion (invenio.modules.authors.testsuite.test_authors_models.TestAuthorsModelsCleanup) ... ok

----------------------------------------------------------------------
Ran 23 tests in 11.274s

OK
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/concurrent/futures/process.py", line 76, in _python_exit
    items = list(_threads_queues.items())
AttributeError: 'NoneType' object has no attribute 'items'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/concurrent/futures/thread.py", line 35, in _python_exit
    items = list(_threads_queues.items())
AttributeError: 'NoneType' object has no attribute 'items'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/concurrent/futures/thread.py", line 35, in _python_exit
    items = list(_threads_queues.items())
AttributeError: 'NoneType' object has no attribute 'items'
```

When I try with B2SHARE testsuite I have yet another error. @dblommesteijn your fix is for this case? 

```
python setup.py test --test-suite invenio.b2share.testsuite

...

running build_ext
Traceback (most recent call last):
  File "setup.py", line 343, in <module>
    'install_lib': _install_lib,
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/setuptools/command/test.py", line 163, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/setuptools/command/test.py", line 37, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'helpers'
```

I ran these tests directly in the Vagrant VM.

**Pull request closed without merging**
