### PR TITLE
Demo fix

### PR DESCRIPTION
**Pull request by nharraud**
* Fixes the docker demo

### CODE REVIEW

**Comment by nharraud** [comment]
@emanueldima could you test this?

It does not however fix the *development environment* install as we should be on bleeding edge for this one in order to detect and fix incompatibilities.

**Comment by nharraud** [comment]
And only *lowest* variant of travis tests will pass for this PR as the other variants use more recent and not backward compatible versions of Invenio 3.

**Comment by emanueldima** [comment]
The container builds and run correctly, but any operation with records fails with HTTP 500. Any idea why?

**Comment by nharraud** [comment]
Strange. I just tested the docker container with GET and PATCH and both are working properly
`curl -XGET 'http://192.168.99.100:5000/api/records/a1c2ef96-a1e4-46fa-9bd7-a2a46d2242d4'`

`curl -v -XPATCH 'http://192.168.99.100:5000/api/records/a1c2ef96-a1e4-46fa-9bd7-a2a46d2242d4' -H "Content-Type:application/json-patch+json" -H "Accept: */*" -d '[{ "op": "replace", "path": "/title", "value": "patch title" }]'`

**Comment by emanueldima** [comment]
Yes, getting an individual record works, but getting /api/records fails now, probably because of the query module.

**Pull request merged**
