### PR TITLE
Allow to have a temporary deposition

### PR DESCRIPTION
**Pull request by SarahBA**
fix for https://github.com/EUDAT-B2SHARE/b2share/issues/552

### CODE REVIEW

**Comment by dblommesteijn** [comment]
Just curious, why have you called variable in `invenio/b2share/modules/b2deposit/restful.py` line 306 `status = open(status_file, 'w+')` `status`? It's a file_handler, not a status.

**Comment by SarahBA** [comment]
I used that file to show the status of the deposition. So its role is basically a 'flag' to show the status!

**Comment by dblommesteijn** [comment]
@SarahBA yes I understand the goal is status, but the variable has another payload. It wasn't obvious to me what happened code wise.

**Comment by dblommesteijn** [comment]
Nevermind!

**Pull request merged**
