### PR TITLE
hiding Unity login option, for now

### PR DESCRIPTION
**Pull request by emanueldima**

### CODE REVIEW

**Comment by cjhak** [comment]
Seems like there is still a Travis problem for the 1.4 branch?

**Comment by cjhak** [comment]
I tried re-running Travis for #632 and #633 but Travis still fails the tests and e.g. #632 is very minor and should pass. @dblommesteijn, is there still some issue with Travis?

**Comment by dblommesteijn** [comment]
@cjhak no Travis works, but the code is in `1.4` and needs to be merged into these pull-requests.

**Comment by emanueldima** [comment]
Already merged via the PR for the new UI

**Comment by dblommesteijn** [comment]
`Linked accounts` page in user settings still has an active link to Unity:
https://b2share.eudat.eu/account/settings/linkedaccounts/

**Pull request closed without merging**
