### PR TITLE
Fix missing location when demo not loaded

### PR DESCRIPTION
**Pull request by emanueldima**
NOT TESTED: this is a suggestion for fixing https://github.com/EUDAT-B2SHARE/b2share/issues/1419, let me know if you'd be happy with it.

### CODE REVIEW

**Comment by nharraud** [comment]
Before doing that I think we could search for the reason why the location is created for the demo and not without it. Just to understand and be sure that we are not adding another bug.

**Comment by thijscobben** [comment]
And/or at least rename the variable "INIT_DB_AND_INDEX_AND_CREATE_EMPTY_LOCATION" or better maybe "INITIALIZE_B2SHARE" and document the things it does.
I would say, we discriminate to an "Empty setup" without load_demo that should work. Apparantly now it doesn't work because the location is not set. Then it makes sense to make two settings/commands: 1. Initialize empty but working system 2. Load demo data

**Comment by nharraud** [comment]
@thijscobben This is what we were doing before (2 setups, one demo one not demo). We should be careful with it because there are at least 4 possible states:
- first start demo
- first start not demo
- restart demo
- restart not demo

We will have to teach our users the commands they have to run. Otherwise every time something goes wrong (ex: not enough disk space so the docker container crashes), the container will be in an unknown state and users will spam us and ask to fix things. IMHO it's better to have a clear documentation which explains every command. We can direct them to the Invenio documentation which is improving fast.

**Comment by emanueldima** [comment]
TODO: investigate where or how the demo creates this default location

**Comment by nharraud** [comment]
@thijscobben found the reason. The CLI command [`b2share demo load_data` adds a location](https://github.com/EUDAT-B2SHARE/b2share/blob/ae98bca812522453a1e5f4e708a881781bec845f/demo/b2share_demo/cli.py#L58).

**Comment by emanueldima** [comment]
How do we solve this? I thing this PR is good enough.

**Comment by nharraud** [comment]
@emanueldima Yes it looks good to me. Did you test it? I am currently rebuilding docker in order to do it.

**Comment by emanueldima** [comment]
No, this is not tested yet, so it should not yet be merged, but it's good that we know how to move on.

**Pull request merged**
