### PR TITLE
Add b2deposit REST API tests

### LINKED ISSUE #693: b2deposit: add functional tests for the REST API

### PR DESCRIPTION
**Pull request by nharraud**
Refactoring helpers and adding tests for the REST API.

There is one test which is not passing, the one for GET `/api/records/` which is supposed to list all the records. On the other hand, the test for `/api/records/<domain_name>` works properly.

(closes #693)

### CODE REVIEW

**Comment by emanueldima** [comment]
But if the tests are not passing the Travis build will fail and our policy is to not merge failing PRs. You should skip the test (add a @nottest decorator to the offending test).

**Comment by nharraud** [comment]
Yes old comment for the `record_id`. I forgot it when I rebased. Removing it right away.
I will comment the test and start working on a fix.

**Comment by dblommesteijn** [comment]
@nharraud Travis gives an error:
`The command "python setup.py test --test-suite invenio.b2share.testsuite" exited with 1.`

**Comment by nharraud** [comment]
Yes I know, working on it. There are multiple issues:
- checksum tests apparently failed because MySQL was not reachable.
- one test failed because of some authentication issue. There might be some configuration issue on the server as this work on my computer. Investigating it.
- the test which I disabled with nottest was run. I will comment this test.

**Comment by nharraud** [comment]
I didn't have an https url configured for `CFG_SITE_SECURE_URL`. This is why the test didn't fail on my laptop, my bad.
As for the MySQL issue, I will wait to see if this happens again.

**Comment by emanueldima** [comment]
@nharraud Is this PR ready to be merged? Are you still working on it? (See the label)

**Comment by cjhak** [comment]
@nharraud For some reason does Github some times automatically add "In progress" in my name. Feel free to remove the label.

**Comment by nharraud** [comment]
Done :)
The last issue was Mysql closing the connection during tests as it was idle, probably during the bibsched tasks. I had to make the timeout longer.

**Pull request merged**
