### PR TITLE
global: register users with B2Access only

### PR DESCRIPTION
**Pull request by nharraud**
* Uses B2Access for new user registration. Encourage users using
  username/password mecanism to connect their B2Share account to
  a B2Access account.

Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>

### CODE REVIEW

**Comment by nharraud** [comment]
Related to #795 #796

A flash message is displayed when the user login using username and password, encouraging him to connect his account to B2Access. The message contains a link enabling to connect the accounts. The username/password can still be used.
The message is less aggressive if the accounts are already connected. It then informs the user that the username password mechanism will be disabled soon.

**Comment by nharraud** [comment]
The feature is working, I just leave it as 'In Progress' so that Emanuel can review it before it is merged.

**Comment by emanueldima** [comment]
@nharraud Any idea why the build fails?

**Comment by nharraud** [comment]
@emanueldima  Sadly no, I didn't have time to look into it yet. It's quite strange that it fails only in `devel` mode. I'll have some time this afternoon to search the problem's origin.

Once it is fixed, could you test it on your laptop? As this is mostly UI and we don't use selenium yet, there is no automatic test checking that it works. The modified pages are the login page, the main page once the login is done and the main page before login (the register link should send you to B2Access).

**Comment by nharraud** [comment]
Ok this is just a dependency issue. The `devel` build uses master branches of some projects like `flask-admin` so that we can be compatible with their next version.
Apparently we fail with current flask-admin master branch. But as long as the release branch passes it should be ok.
Just to be sure I ran again the travis tests on a previously passing commit. It failed (https://travis-ci.org/EUDAT-B2SHARE/b2share/jobs/85269123)

**Comment by emanueldima** [comment]
Yes, it's not the first time this happens. So far, Travis didn't help much in finding bugs but kept us from moving faster.

**Pull request merged**
