### PR TITLE
Update latest_deposits.py

### PR DESCRIPTION
**Pull request by llehtine**
this should fix the latest deposits showing 4 first deposits

### CODE REVIEW

**Comment by emanueldima** [comment]
Yes, I can see why

**Comment by dblommesteijn** [comment]
Why did we merge a pull-request that was failing Travis?

**Comment by emanueldima** [comment]
There's no way this fix could have crashed travis. I think travis didn't like the fact that I hastily removed the branch, let's restart it.

**Comment by emanueldima** [comment]
It's possible that an update of some python package broke the travis build; this upstream fix might be related: https://github.com/inveniosoftware/invenio/commit/f7c3f768eefc658a70452eaa617a2035175c25b7

**Pull request merged**
