### PR TITLE
WIP: RestAPI unit-tests placeholders

### PR DESCRIPTION
**Pull request by dblommesteijn**
Work in progress, test driven development and unit-tests for #480. The tests are failing because there is no implementation, yet. Do not merge into `master` branch.

Run tests via:
```bash
python setup.py test -s invenio.b2share.testsuite.test_b2deposit_restapi
```

### CODE REVIEW

**Comment by dblommesteijn** [comment]
Collected the latest API changes.

**Comment by dblommesteijn** [comment]
Basic unit testing now works for the RestAPI. I still need to complete the set, so don't merge please!

**Comment by dblommesteijn** [comment]
I've discovered an issue with the automated testing, `bibsched` will lock to 100% load when the test have run. Not sure how to solve it yet.

**Comment by emanueldima** [comment]
Add the tests anyway but comment out some lines so that they won't run, for now?

**Comment by dblommesteijn** [comment]
@emanueldima that's not a bad idea. I'll do that.

**Comment by dblommesteijn** [comment]
@emanueldima I've not yet managed the merge, you can merge 2.0 into master ignoring this pull-request.

**Comment by cjhak** [comment]
@dblommesteijn, can we remove (close) this pull request? It's not very relevant for the 1.6 branch any longer.

**Comment by dblommesteijn** [comment]
I agree, closing it.

**Pull request closed without merging**
