### PR TITLE
global: fix recursive imports

### PR DESCRIPTION
**Pull request by nharraud**
* FIX Fixes recursive imports in b2share records module.

Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>

### CODE REVIEW

**Comment by emanueldima** [comment]
I suspect travis fails because of the recent chages in this module: https://github.com/inveniosoftware/invenio-files-rest

**Comment by nharraud** [comment]
Yes, fixing it too.

**Comment by jirikuncar** [comment]
@nharraud @emanueldima I have recently released updated version of Invenio-Files-REST. I hope it solves your problem with failing tests.

**Comment by nharraud** [comment]
@jirikuncar I had been warned beforehand by @lnielsen that the API would change. It is just that the PUT /api/files works a little differently. The fix on our side should not be big. I already finished fixing the tests.

**Comment by thijscobben** [comment]
Trivial and important fix

**Pull request merged**
